runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: main.app
  login: admin

- url: /data/.*
  script: main.app
  login: admin

- url: /public/data/.*
  script: main.app
  login: optional

- url: /mailfeed/.*
  script: main.app
  login: optional

- url: /oauth.*
  script: main.app
  login: admin

- url: /assets
  static_dir: assets
  login: admin

- url: /.*
  static_files: assets/index.html
  upload: assets/index.html
  login: admin
