runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail

handlers:
- url: /assets
  static_dir: assets
  login: admin

- url: /
  static_files: assets/index.html
  upload: assets/index.html
  login: admin

- url: /mail
  static_files: assets/index.html
  upload: assets/index.html
  login: admin

- url: /favicon.ico
  static_files: assets/rss.png
  upload: assets/rss.png

- url: /.*
  script: main.app

- url: /_ah/mail/.+
  script: main.app
  login: admin
